#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill ~/Pictures/wallpaper2.jpg ~/Pictures/wallpaper.jpg
picom &
redshift &
~/.config/polybar/start.sh

xsetroot -cursor_name left_ptr

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX
bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX

bspc config border_width          3
bspc config window_gap            12
bspc config focus_follows_pointer true

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
